app:
  port: 8000
  page_size: 5
  templates_dir: "service/web/adapter/templates/"
db:
  host: 127.0.0.1
  port: 3306
  user: "test_user"
  password: "test_pass"
  database: "lr_event_book"
mq:
  brokers:
    - localhost:9094
  topic: "lr-book-searches"
remote:
  trend_url: "http://localhost:8001/trends"
  rec_url: "http://localhost:8002/recommendations?uid="